from pathlib import Path
p=Path('/Users/brian/.codex/visualizations/2026/09/07/01a07dce-ee45-77f1-a36d-c2efbed2db4d/coxswain-live-display.html')
s=p.read_text()
s=s.replace('</style>','''#cs-live header .customize{background:transparent;color:#c8e3e9;border:1px solid #73929e;border-radius:20px;padding:8px 12px;min-height:44px;font:inherit;cursor:pointer}#cs-live footer{padding-top:10px}#cs-live footer button{flex:1}#cs-live footer .end{background:#622b32;border-color:#bd838b}#cs-live dialog{background:#123f51;color:#fff;border:1px solid #73929e;border-radius:20px;padding:24px;max-width:min(340px,80%);font-family:inherit}#cs-live dialog::backdrop{background:#001019b3}#cs-live dialog h3{margin:0 0 12px;font-size:22px}#cs-live dialog button{background:#204d60;color:white;border:1px solid #73929e;border-radius:24px;padding:12px 16px;min-height:48px;font-size:15px;cursor:pointer}#cs-live dialog .confirm-end{background:#622b32}#cs-live dialog .actions{display:flex;flex-wrap:wrap;gap:8px}#cs-live .number{letter-spacing:-.035em}#cs-live .label{margin-top:4px}#cs-live footer button:disabled{opacity:.55;cursor:default}
</style>''')
s=s.replace('<span>● Connected</span></header>','<span>● Connected</span><button type="button" class="customize">Edit display</button></header>')
s=s.replace('<footer><button type="button" class="customize">Edit display</button><button type="button" class="pause">Pause</button></footer>','''<footer><button type="button" class="pause">Pause</button><button type="button" class="end">End session</button></footer>
<dialog aria-labelledby="cs-end-title"><h3 id="cs-end-title">End this session?</h3><p>Finish rowing and review your workout.</p><div class="actions"><button type="button" class="cancel-end">Keep rowing</button><button type="button" class="confirm-end">End session</button></div></dialog>''')
a=s.index('function fit()');b=s.index('function render()',a)
s=s[:a]+'''function fit(){const cells=[...grid.children];cells.forEach((cell,i)=>{const m=catalog[slots[i]],n=cell.querySelector('.number'),label=cell.querySelector('.label');const w=cell.clientWidth-24,h=cell.clientHeight-label.offsetHeight-24;const family=getComputedStyle(n).fontFamily;ctx.font='500 100px '+family;const stable=m[1].replace(/[0-9]/g,'8');const measure=ctx.measureText(stable).width;const size=Math.floor(Math.min(h/1.05,w*100/measure));n.style.fontSize=Math.max(12,size)+'px';})}
''' + s[b:]
s=s.replace('render();new ResizeObserver(fit).observe(grid);', '''const dialog=root.querySelector('dialog');root.querySelector('.end').onclick=()=>{editor.hidden=true;root.querySelector('.cancel-end').textContent=paused?'Stay paused':'Keep rowing';dialog.showModal()};root.querySelector('.cancel-end').onclick=()=>dialog.close();root.querySelector('.confirm-end').onclick=()=>{dialog.close();root.querySelector('.session').textContent='SESSION COMPLETE';root.querySelector('.pause').disabled=true;root.querySelector('.end').disabled=true;};
render();new ResizeObserver(fit).observe(grid);if(document.fonts)document.fonts.ready.then(fit);''')
p.write_text(s)
